### ISSUE TITLE
RoyaltiesRegistry contract allows to set royalties multiple times and change it in between trades

### ISSUE THREAD

**Issue by pgebal** [rarible/protocol-contracts#111]
When I'm referring to contract owner I mean an owner in the meaning of `@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable`

For setting up royalties on an external collection a user can call `RoyaltiesRegistry.setRoyaltiesByToken`
For the call to succeed caller has to be either [owner of `RoyaltiesRegistry` contract or owner of the token contract.](https://github.com/rarible/protocol-contracts/blob/afc080735d7d8373fe51c7641787078add06f9b2/royalties-registry/contracts/RoyaltiesRegistry.sol#L92)

Protocol contracts allow to call those functions multiple times, which means that token contract owner can change royalties in between exchange sales, potentially setting royalties up to 99.99%.

**Comment by disenotov** [comment]
Hello!
well, this is an intentional behaviour, but can probably be abused by malicious collection owner (tho the maximum royalties in protocol are 50% and something like this probably gonna hurt artists' reputation more)
what do you think would be the best way to fix this?
