### ISSUE TITLE
Royalties for polygon 

### ISSUE THREAD

**Issue by igbodani** [rarible/protocol-contracts#122]
Hello,

I am trying to implement the rarible royalties interface for my ERC720 and ERC1155 tokens, but I wasn't sure if my contract would be able to call the rarible contracts if I deployed to the polygon main-net,  does the rarible royalties contracts  support polygon chain ?

Thank you

**Comment by disenotov** [comment]
Hello!
All our contracts (including royalties contract) are deployed on the polygon main net as well as ethereum main net. So on polygon we support everything we support on ethereum.

**Comment by igbodani** [comment]
Thank you for your reply
