### ISSUE TITLE
Orders are always valid if the maker is 0 and the signature is empty.

### ISSUE THREAD

**Issue by e-nikolov** [rarible/protocol-contracts#134]
In the [OrderValidator.validate()](https://github.com/rarible/protocol-contracts/blob/master/exchange-v2/contracts/OrderValidator.sol#L30) function, I think the order will always be considered valid if the order.maker is set to 0 and the signature is empty.

Because `signer` remains 0 if the signature is empty and then the check

```
if  (signer != order.maker)
```

will be

```
if (0 != 0)
```
which will skip the body of the if, and the validate() function won't fail.

Maybe this isn't really an issue because the transaction will fail at some point later anyway, but it's probably safer to 
`require (order.maker != address(0))`

**Comment by disenotov** [comment]
hi!
it shouldn't be a problem, but added require anyway.
Thanks!
