### ISSUE TITLE
Provide a brownie package of the rarible protocol contracts

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/protocol-contracts#150]
I know the Typescript SDK is the preferred route to all things Rarible Protocol, but I did have a need to play with the Rarible contracts directly and I had tried to use brownie to do that.  I quickly ran into issues, so opened a ticket for the team to consider packaging the contracts in a brownie friendly format.  Right now the rarible protocols-contracts repo doesn't even have a release yet,  so I can't even try to import it.

For a well documented example see the work by the Chainlink team and Patrick Collins show how to make NFTs while also showing how to use the Chainlink products.   I think a Rarible equivalent of say an OpenZeppelin NFT with the Rarible Royalties would be a great demo (something I was trying to do.) The more "features" you can sell that the protocol supports, the more folks that may go all in on the Rarible Protocol. 

- https://github.com/smartcontractkit/chainlink-mix
- https://www.youtube.com/watch?v=p36tXHX1JD8&ab_channel=PatrickCollins
- https://github.com/eth-brownie/brownie

I would see this as helpful for future Hackathons etc as you can get some Python developers playing with the Rarible Protocol.

**Comment by bobwith2bees** [comment]
Consider this a "would be nice" feature request.   

Given the existing protocol-contracts repo easily builds the contract ABI json files with the README.md, a user can jump directly to a web3 package (pick your language) and go from there.   It's not all in your IDE, but workable.

**Comment by disenotov** [comment]
hi, thanks for the suggestion!
we are going to think about implementing it

**Comment by SKonstantinS** [comment]
We create the task, I close issue
