### ISSUE TITLE
Minimum number of contracts to deploy

### ISSUE THREAD

**Issue by damianlluch** [rarible/protocol-contracts#158]
Hi, I have previously asked if there was any architecture diagram to understand how the contracts work as a whole and I have been told that there is no such diagram.

Looking at the directions of deployment in the different networks.
In Polygon for example there are these 4 contracts deployed:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/1463804/174566778-8cf8a773-9a1a-48e8-b8a5-dd4e09fb0dde.png">

Now at Testnet (Rinkeby, Mumbai) these contracts are deployed:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1463804/174566902-2d3f9edc-4d04-4dfe-a51e-69bed09dc5b8.png">

Why has this been done? What are Asset Contract ERC-721 and Asset Contract ERC-1155 for? At least in Polygon they are not verified.

In testnet there is this contract NFT Transfer Proxy (for Approvals) while in Polygon it is specified as Transfer Proxies. What is the difference?

thanks

**Comment by disenotov** [comment]
hi!
sorry for the long wait.
yes, as i can see there is a problem with naming of contracts in this documentation. 
for example Asset Contract ERC-721 and Asset Contract ERC-1155 are Rarible erc-721 and erc-1155 collections respectively.
the same contracts are deployed on all evm-based chain, this document should be fixed.
what is the question now? what contracts need to be deployed?

**Comment by damianlluch** [comment]
> i think it's easier to understand the structure if we omit TransparentUpgradeable proxies from this scheme. so, the main contract is ExchangeV2 (upgradeable), all trades happen using this contract.
> 
> when the trade includes ERC-721 or ERC-1155, ExchangeV2 contract tries to get royalties for them using RoyaltiesRegistry contract (upgradeable too)
> 
> TransferProxy is a contract for nfts, users approve their nfts on this contract, so then ExchangeV2 contract is able to transfer these nfts when trade is happening. ERC20TransferProxy is the same but for the erc-20 tokens.
> 
> ERC721LazyMintTransferProxy, ERC1155LazyMintTransferProxy - are the transfer proxies for the lazy minting, they work a little differently, but i don't think it's important right now
> 
> then there are factories: ERC721RaribleFactoryC2, ERC1155RaribleFactoryC2. they can create beacon proxies for the tokens. so for every factory there is:
> 
> * implementation contract (e.g. ERC721)
> * beacon contract  that stores implementation address
> 
> when user calls createToken() using one of the factories, the proxy is created that knows about beacon address. so every proxy created from these factories knows about the same beacon which stores implementation address. then if we need to upgrade implementation for tokens - it's need to be done for the beacons only (one for 721, one for 1155)
> 
> lastly there are separate rarible collections : ERC1155Rarible and ERC721RaribleMinimal (upgradeable using TransparentUpgradeable proxies)
> 
> hope that helps a little :)

Send me an email and I will share with you the diagram I have made so you can publish it to make the protocol more understandable. We will modify it if we need to.

**Comment by SKonstantinS** [comment]
Hi, I like your idea. Please send me: k.shcherbakov@rarible.com.
