### ISSUE TITLE
Doubt about internal function of royalties

### ISSUE THREAD

**Issue by damianlluch** [rarible/protocol-contracts#162]
What is the purpose of this function?

thank you

```
function _updateAccount(uint256 _id, address _from, address _to) internal {
        uint length = royalties[_id].length;
        for(uint i = 0; i < length; i++) {
            if (royalties[_id][i].account == _from) {
                royalties[_id][i].account = payable(address(uint160(_to)));
            }
        }
    }
```
https://github.com/rarible/protocol-contracts/blob/787c51853265a70e8e9c84dbc7f24f80d8003a25/royalties/contracts/impl/AbstractRoyalties.sol#L22

**Comment by SKonstantinS** [comment]
Hi, Thank you for your interest in the project.
Sorry for the long answer.
The main purpose of this method is to change the royalties account address to a new one specified in the parameter _to

**Comment by SKonstantinS** [comment]
Please, if there are no other questions. Please close issue, thank You.
