### ISSUE TITLE
Verification of contract source in polygon scan

### ISSUE THREAD

**Issue by CryptoNicholas** [rarible/protocol-contracts#254]
I am the creator and owner of the NFTS CryptoNicholas collection, and I use the safepall wallet, for several days now, my collection has disappeared from the wallet, when I contacted the wallet support, I found out that the problem is not validating the source code that is in rarible after  nft minting failed pls check my problem ،And confirm my source code؛thanks
Address conteract collection:
https://rarible.com/collection/polygon/0x93e992922fbb0212cf4e1c941e284fd2eae3ca05/items
The link that SFP wallet support sent to investigate the cause of the problem:
https://gopluslabs.io/nft-security-detection/137/0x93e992922fbb0212cf4e1c941e284fd2eae3ca05

**Comment by evgenynacu** [comment]
@CryptoNicholas thanks for the information
Will try to resolve this soon

**Comment by CryptoNicholas** [comment]
Hi, thank you for your help

در تاریخ چهارشنبه ۱ نوامبر ۲۰۲۳،‏ ۱۲:۰۷ Eugene Nacu <
***@***.***> نوشت:

**Comment by disenotov** [comment]
@CryptoNicholas  hi! there was a problem on polygon scan with verifying beaconProxy contracts. i fixed it, now your collection is verified https://polygonscan.com/address/0x93e992922fbb0212cf4e1c941e284fd2eae3ca05#code 
please feel free to reopen the issue if there are other problems

**Comment by CryptoNicholas** [comment]
I really thank you for your kindness, you did a great job for me, you are
amazing.👌❤️

در تاریخ چهارشنبه ۱ نوامبر ۲۰۲۳،‏ ۱۷:۱۶ Dmitry Senotov <
***@***.***> نوشت:

**Comment by CryptoNicholas** [comment]
I really thank you for your kindness, you did a great job for me, you are amazing.👌❤️
