### ISSUE TITLE
EIP1271 signature verification issue

### ISSUE THREAD

**Issue by k06a** [rarible/protocol-contracts#60]
I see you used `ECDSA.recover()` to validate EOA signature:

https://github.com/rarible/protocol-contracts/blob/8b686c3316fcb6ad82a50a42f84ddecfcdc17d27/exchange-v2/contracts/OrderValidator.sol#L28-L37

Your fallback logic is to validate if signature is smart-contract based (according to EIP1271). But `recover()` method will revert in case of invalid signature (see [LibSignature.sol](https://github.com/rarible/protocol-contracts/blob/8b686c3316fcb6ad82a50a42f84ddecfcdc17d27/exchange-v2/contracts/lib/LibSignature.sol), potentially copied from OZ: [ECDSAUpgradeable.sol#v3.4.0](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/efde58409783cccc7fd47c7ad9e095101ffb2faa/contracts/cryptography/ECDSAUpgradeable.sol)). You have to switch to newer version to be able validate signature without internal revert in library (upcoming 4.3.0 release branch: [ECDSAUpgradeable.sol#release-v4.3](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/release-v4.3/contracts/utils/cryptography/ECDSAUpgradeable.sol)). Moreover I suggest you to check this new library to validate both EOA and SC based signatures: [SignatureCheckerUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/1ea0eed769fae4e22efc4f63d970b3715e783669/contracts/utils/cryptography/SignatureCheckerUpgradeable.sol).

**Comment by mudgen** [comment]
In the case of `OrderValidator.sol` it seems fine to me if `recover()` reverts internally.  Is there some reason it shouldn't?

I noticed that [ECDSAUpgradeable.sol#release-v4.3](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/release-v4.3/contracts/utils/cryptography/ECDSAUpgradeable.sol) supports [compact signatures](https://eips.ethereum.org/EIPS/eip-2098) which is nice.

**Comment by k06a** [comment]
@mudgen but you will not check smart contract signature in that case

**Comment by mudgen** [comment]
@k06a Yes, I see.   So you would still want to call `isValidSignature` with the signature in case the contract validates the signature in a different way than `recover()`.

**Comment by k06a** [comment]
Exactly, that is what I meant when created this issue.

**Comment by mudgen** [comment]
Cool, makes sense :+1:

**Comment by k06a** [comment]
I see issue was fixed here: https://github.com/rarible/protocol-contracts/pull/222
