### ISSUE TITLE
Add KCC(KuCoin Community Chain) support

### ISSUE THREAD

**Issue by enekoastorkiza** [rarible/protocol-contracts#63]
TokenName: KuCoin Token
ChainName: KCC

Symbol: KCS
Documentation: https://docs.kcc.io/
Reason: KCC is a high-performance and decentralized public chain built by KCS’ and KuCoin’s fan communities.
Developed based on go-there with the purpose of providing community users with a higher-speed, convenient and low-cost blockchain user experience.

Fully compatible with Ethereum and ERC-20 smart contracts, extremely low costs in migration.

**Comment by 0xmatt1** [comment]
I second this

**Comment by evgenynacu** [comment]
Hey
We are currently working on the polygon support.
Then we will review all other evm compatible chains and will prioritize them.
