### ISSUE TITLE
This should be payable?

### ISSUE THREAD

**Issue by iamgenchi** [rarible/protocol-contracts#86]
I think https://github.com/rarible/protocol-contracts/blob/master/royalties/contracts/impl/AbstractRoyalties.sol#L26 should be payable

```
royalties[_id][i].account = payable(address(uint160(_to)));
```
instead of
```
royalties[_id][i].account = address(uint160(_to));
```

As you can see in [LibPart](https://github.com/rarible/protocol-contracts/blob/master/royalties/contracts/LibPart.sol#L9).
```
    struct Part {
        address payable account;
        uint96 value;
    }
```

**Comment by mustafa-boorenie** [comment]
I am having the same issue and its being highlighted in red on VS Code. Any solutions?

**Comment by disenotov** [comment]
hello!
solidity compiler 0.7.6 doesn't highlight this as error, can you make sure you use it for your workspace?
As for the error itself, i think it's pretty minor, but we will fix it with the next exchangeV2 update

**Comment by mustafa-boorenie** [comment]
> hello!
> 
> solidity compiler 0.7.6 doesn't highlight this as error, can you make sure you use it for your workspace?
> 
> As for the error itself, i think it's pretty minor, but we will fix it with the next exchangeV2 update

`royalties[_id][i].account = payable(address(uint160(_to)));`

I've been able to fix it by modifying the AbstractRoyalties.sol file and wrapping the _to address in payable. 

Now it works fine for me.
