### ISSUE TITLE
Question about auction creating on rarible contracts

### ISSUE THREAD

**Issue by kolberszymon** [rarible/protocol-contracts#99]
Hey guys!
Firstly, you're creating amazing job! I'm currently writing rarible tutorials and was wondering is it possible to create an auction using Rarible protocol? If so where I can find the contract?

Thanks for help!
Szymon

**Comment by SKonstantinS** [comment]
Thanks for your interest in the project, if relevant here is a link to the contract
https://github.com/rarible/protocol-contracts/tree/master/auction
